# Site wide configuration

title: "LJournal"
description: "Blog and Journal"
logo: journal.png
teaser: journal.png
locale: en_US
url: "https://brianlusina.github.io/LJournal"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Site owner
owner:
  name: "Brian Lusina"
  web: "https://thelusina.netlify.com"
  twitter: "brianlusina"
  bio: "The Lusina"
  avatar: "bio-photo.jpg" # 160x160 px image for author byline
  google:
    plus: 102302755150765254402
    ad-client: ""
    ad-slot: 
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
