version: 2
jobs:
        build:
                working_directory: ~/ljournal
                docker:
                        image: circleci/node:7.10
                environment:
                        GA_ANALYTICS: $GA_ANALYTICS

                steps:
                        - checkout
                        - restore_cache:
                                key: LJournal-{{ checksum "package.json"  }}-{{ .Branch }}
                                keys:
                                        - v1-dependencies-{{ checksum "package.json" }}
                                        # fallback to using the latest cache if no exact match is found 
                                        - v1-dependencies-
                        - run: 
                                name: Download dependencies
                                command: yarn install

                        - save_cache:
                                key: LJournal-{{ checksum "package.json" }}-{{ .Branch }}
                                paths:
                                        - node_modules
                                keys:
                                        - v1-dependencies-{{ checksum "package.json" }}

                        - persist_to_workspace:
                                root: .
                                paths: .

        test:
                working_directory: ~/ljournal
                docker:
                        image: circleci/node:7.10
                steps:
                        - attach_workspace:
                                at: .
                        
                        - restore_cache:
                                key: LJournal-{{ checksum "package.json" }}-{{ .Branch }}
                                keys:
                                        - v1-dependencies-{{ checksum "package.json" }}

                        - run:
                                name: Run tests
                                command:
                                        yarn test
